version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi.hole
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8765:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'your_secret_password'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    extra_hosts:
      - "pi.vrax.de:192.168.2.150"
      - "office.vrax.de:192.168.2.150"
      - "home.vrax.de:192.168.2.150"
      - "webwatch.vrax.de:192.168.2.150"
      - "pihole.local:192.168.2.150"
      - "pihole:192.168.2.150"      
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
